package com.passport.service.impl;

import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import com.passport.model.*;
import com.passport.repository.UserRepository;
import com.passport.service.PdfGenerationService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.awt.Color;  // ← FIXED: Use java.awt.Color, not com.lowagie.text.Color
import java.io.ByteArrayOutputStream;
import java.util.List;

@Service
public class PdfGenerationServiceImpl implements PdfGenerationService {

    @Autowired
    private UserRepository userRepository;

    private static final Font TITLE_FONT = new Font(Font.HELVETICA, 22, Font.BOLD, new Color(30, 58, 138));
    private static final Font HEADING_FONT = new Font(Font.HELVETICA, 13, Font.BOLD, new Color(37, 99, 235));
    private static final Font SUBHEADING_FONT = new Font(Font.HELVETICA, 11, Font.BOLD, new Color(55, 65, 81));
    private static final Font NORMAL_FONT = new Font(Font.HELVETICA, 10, Font.NORMAL, new Color(75, 85, 99));
    private static final Font SMALL_FONT = new Font(Font.HELVETICA, 9, Font.NORMAL, new Color(100, 116, 139));

    @Override
    public byte[] generateResumePdf(Long userId) {
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new RuntimeException("User not found"));

        try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
            Document document = new Document(PageSize.A4, 50, 50, 50, 50);
            PdfWriter.getInstance(document, baos);
            document.open();

            // HEADER
            addHeader(document, user);

            // SUMMARY
            if (user.getSummary() != null && !user.getSummary().isEmpty()) {
                addSectionHeading(document, "PROFESSIONAL SUMMARY");
                Paragraph summary = new Paragraph(user.getSummary(), NORMAL_FONT);
                summary.setSpacingAfter(12);
                document.add(summary);
            }

            // EDUCATION
            List<Education> educations = user.getEducations();
            if (educations != null && !educations.isEmpty()) {
                addSectionHeading(document, "EDUCATION");
                for (Education edu : educations) {
                    addEducationEntry(document, edu);
                }
            }

            // EXPERIENCE
            List<Experience> experiences = user.getExperiences();
            if (experiences != null && !experiences.isEmpty()) {
                addSectionHeading(document, "EXPERIENCE");
                for (Experience exp : experiences) {
                    addExperienceEntry(document, exp);
                }
            }

            // SKILLS
            List<Skill> skills = user.getSkills();
            if (skills != null && !skills.isEmpty()) {
                addSectionHeading(document, "SKILLS");
                addSkillsSection(document, skills);
            }

            // PROJECTS
            List<Project> projects = user.getProjects();
            if (projects != null && !projects.isEmpty()) {
                addSectionHeading(document, "PROJECTS");
                for (Project proj : projects) {
                    addProjectEntry(document, proj);
                }
            }

            // CERTIFICATES
            List<Certificate> certificates = user.getCertificates();
            if (certificates != null && !certificates.isEmpty()) {
                addSectionHeading(document, "CERTIFICATIONS");
                for (Certificate cert : certificates) {
                    addCertificateEntry(document, cert);
                }
            }

            // FOOTER
            Paragraph footer = new Paragraph("\nGenerated by Competency Passport",
                    new Font(Font.HELVETICA, 8, Font.ITALIC, new Color(156, 163, 175)));
            footer.setAlignment(Element.ALIGN_CENTER);
            document.add(footer);

            document.close();
            return baos.toByteArray();

        } catch (Exception e) {
            throw new RuntimeException("Failed to generate PDF: " + e.getMessage());
        }
    }

    private void addHeader(Document doc, User user) throws DocumentException {
        // Name
        Paragraph name = new Paragraph(user.getFullName().toUpperCase(), TITLE_FONT);
        name.setAlignment(Element.ALIGN_CENTER);
        doc.add(name);

        // Contact line
        StringBuilder contact = new StringBuilder();
        if (user.getEmail() != null) contact.append(user.getEmail());
        if (user.getPhone() != null) contact.append("  |  ").append(user.getPhone());
        if (user.getLocation() != null) contact.append("  |  ").append(user.getLocation());

        Paragraph contactPara = new Paragraph(contact.toString(), SMALL_FONT);
        contactPara.setAlignment(Element.ALIGN_CENTER);
        contactPara.setSpacingAfter(3);
        doc.add(contactPara);

        // Social links
        StringBuilder social = new StringBuilder();
        if (user.getGithubUsername() != null) {
            social.append("github.com/").append(user.getGithubUsername());
        }
        if (user.getLinkedinId() != null) {
            if (!social.isEmpty()) social.append("  |  ");
            social.append("linkedin.com/in/").append(user.getLinkedinId());
        }
        if (user.getLeetcodeUsername() != null) {
            if (!social.isEmpty()) social.append("  |  ");
            social.append("leetcode.com/").append(user.getLeetcodeUsername());
        }

        if (!social.isEmpty()) {
            Paragraph socialPara = new Paragraph(social.toString(),
                    new Font(Font.HELVETICA, 9, Font.ITALIC, new Color(37, 99, 235)));
            socialPara.setAlignment(Element.ALIGN_CENTER);
            socialPara.setSpacingAfter(3);
            doc.add(socialPara);
        }

        // Headline
        if (user.getHeadline() != null) {
            Paragraph headline = new Paragraph(user.getHeadline(),
                    new Font(Font.HELVETICA, 11, Font.ITALIC, new Color(71, 85, 105)));
            headline.setAlignment(Element.ALIGN_CENTER);
            headline.setSpacingAfter(12);
            doc.add(headline);
        }

        // Blue line separator
        PdfPTable line = new PdfPTable(1);
        line.setWidthPercentage(100);
        PdfPCell cell = new PdfPCell();
        cell.setBorderColor(new Color(37, 99, 235));
        cell.setBorderWidthTop(2);
        cell.setBorder(Rectangle.TOP);
        cell.setFixedHeight(5);
        line.addCell(cell);
        doc.add(line);
    }

    private void addSectionHeading(Document doc, String text) throws DocumentException {
        Paragraph heading = new Paragraph(text, HEADING_FONT);
        heading.setSpacingBefore(14);
        heading.setSpacingAfter(6);
        doc.add(heading);

        PdfPTable line = new PdfPTable(1);
        line.setWidthPercentage(100);
        PdfPCell cell = new PdfPCell();
        cell.setBorderColor(new Color(229, 231, 235));
        cell.setBorderWidthBottom(1);
        cell.setBorder(Rectangle.BOTTOM);
        cell.setFixedHeight(2);
        line.addCell(cell);
        doc.add(line);
    }

    private void addEducationEntry(Document doc, Education edu) throws DocumentException {
        PdfPTable table = new PdfPTable(2);
        table.setWidthPercentage(100);
        table.setSpacingAfter(8);

        PdfPCell left = new PdfPCell();
        left.setBorder(Rectangle.NO_BORDER);
        left.addElement(new Paragraph(edu.getInstitution(), SUBHEADING_FONT));
        left.addElement(new Paragraph(
                edu.getDegree() + (edu.getFieldOfStudy() != null ? " in " + edu.getFieldOfStudy() : ""),
                NORMAL_FONT));
        if (edu.getGrade() != null) {
            left.addElement(new Paragraph("Grade: " + edu.getGrade(), SMALL_FONT));
        }
        table.addCell(left);

        PdfPCell right = new PdfPCell();
        right.setBorder(Rectangle.NO_BORDER);
        right.setHorizontalAlignment(Element.ALIGN_RIGHT);
        String dates = (edu.getStartDate() != null ? edu.getStartDate() : "") + " - " +
                (edu.getEndDate() != null ? edu.getEndDate() : "Present");
        Paragraph datePara = new Paragraph(dates, SMALL_FONT);
        datePara.setAlignment(Element.ALIGN_RIGHT);
        right.addElement(datePara);
        table.addCell(right);

        doc.add(table);
    }

    private void addExperienceEntry(Document doc, Experience exp) throws DocumentException {
        PdfPTable table = new PdfPTable(2);
        table.setWidthPercentage(100);
        table.setSpacingAfter(8);

        PdfPCell left = new PdfPCell();
        left.setBorder(Rectangle.NO_BORDER);
        left.addElement(new Paragraph(exp.getTitle(), SUBHEADING_FONT));
        left.addElement(new Paragraph(exp.getCompany() + " | " + exp.getEmploymentType(), NORMAL_FONT));
        if (exp.getDescription() != null) {
            Paragraph desc = new Paragraph(exp.getDescription(), NORMAL_FONT);
            desc.setSpacingBefore(3);
            left.addElement(desc);
        }
        table.addCell(left);

        PdfPCell right = new PdfPCell();
        right.setBorder(Rectangle.NO_BORDER);
        right.setHorizontalAlignment(Element.ALIGN_RIGHT);
        String dates = (exp.getStartDate() != null ? exp.getStartDate() : "") + " - " +
                (exp.getIsCurrent() ? "Present" : (exp.getEndDate() != null ? exp.getEndDate() : ""));
        Paragraph datePara = new Paragraph(dates, SMALL_FONT);
        datePara.setAlignment(Element.ALIGN_RIGHT);
        right.addElement(datePara);
        table.addCell(right);

        doc.add(table);
    }

    private void addSkillsSection(Document doc, List<Skill> skills) throws DocumentException {
        PdfPTable table = new PdfPTable(3);
        table.setWidthPercentage(100);
        table.setSpacingAfter(10);

        for (Skill skill : skills) {
            PdfPCell cell = new PdfPCell();
            cell.setBorder(Rectangle.NO_BORDER);
            cell.setPadding(4);
            cell.addElement(new Paragraph("• " + skill.getSkillName(), NORMAL_FONT));

            StringBuilder dots = new StringBuilder();
            for (int i = 1; i <= 5; i++) {
                dots.append(i <= skill.getProficiencyLevel() ? "●" : "○");
            }
            cell.addElement(new Paragraph(dots.toString(),
                    new Font(Font.HELVETICA, 8, Font.NORMAL, new Color(37, 99, 235))));
            table.addCell(cell);
        }

        // Fill empty cells
        int remainder = skills.size() % 3;
        for (int i = 0; i < (remainder == 0 ? 0 : 3 - remainder); i++) {
            PdfPCell empty = new PdfPCell();
            empty.setBorder(Rectangle.NO_BORDER);
            table.addCell(empty);
        }

        doc.add(table);
    }

    private void addProjectEntry(Document doc, Project proj) throws DocumentException {
        PdfPTable table = new PdfPTable(1);
        table.setWidthPercentage(100);
        table.setSpacingAfter(8);

        PdfPCell cell = new PdfPCell();
        cell.setBorder(Rectangle.NO_BORDER);
        cell.addElement(new Paragraph(proj.getTitle(), SUBHEADING_FONT));

        if (proj.getIsFeatured()) {
            cell.addElement(new Paragraph("Featured Project",
                    new Font(Font.HELVETICA, 8, Font.ITALIC, new Color(234, 88, 12))));
        }

        if (proj.getDescription() != null) {
            cell.addElement(new Paragraph(proj.getDescription(), NORMAL_FONT));
        }
        if (proj.getTechnologies() != null) {
            cell.addElement(new Paragraph("Tech: " + proj.getTechnologies(), SMALL_FONT));
        }
        if (proj.getGithubUrl() != null) {
            cell.addElement(new Paragraph("GitHub: " + proj.getGithubUrl(), SMALL_FONT));
        }
        if (proj.getLiveUrl() != null) {
            cell.addElement(new Paragraph("Live: " + proj.getLiveUrl(), SMALL_FONT));
        }

        table.addCell(cell);
        doc.add(table);
    }

    private void addCertificateEntry(Document doc, Certificate cert) throws DocumentException {
        PdfPTable table = new PdfPTable(2);
        table.setWidthPercentage(100);
        table.setSpacingAfter(6);

        PdfPCell left = new PdfPCell();
        left.setBorder(Rectangle.NO_BORDER);
        left.addElement(new Paragraph(cert.getTitle(), SUBHEADING_FONT));
        left.addElement(new Paragraph(cert.getIssuer(), NORMAL_FONT));
        if (cert.getCredentialId() != null) {
            left.addElement(new Paragraph("ID: " + cert.getCredentialId(), SMALL_FONT));
        }
        table.addCell(left);

        PdfPCell right = new PdfPCell();
        right.setBorder(Rectangle.NO_BORDER);
        right.setHorizontalAlignment(Element.ALIGN_RIGHT);
        String dates = "Issued: " + (cert.getIssueDate() != null ? cert.getIssueDate() : "N/A");
        if (cert.getExpiryDate() != null) dates += " | Expires: " + cert.getExpiryDate();
        right.addElement(new Paragraph(dates, SMALL_FONT));
        table.addCell(right);

        doc.add(table);
    }
}